[build]
  # Use yarn commands, relying on .yarnrc to pick local yarn 1 binary
  command = "yarn install && yarn build"

[build.environment]
  # Disable Corepack auto yarn version management (optional but recommended)
  NETLIFY_USE_YARN2 = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"